app/urls.py
from django.urls import path

from . import views

app_name = "hospital"

urlpatterns = [
    path("", views.index, name="index"),
    # doctor
    path("doctors/", views.DoctorListView.as_view(), name="doctors"),
    path("doctors/create", views.DoctorCreateView.as_view(), name="create_doc"),
    path("doctors/<pk>/update", views.DoctorUpdateView.as_view(), name="update_doc"),
    path("doctors/<pk>/delete", views.DoctorDeleteView.as_view(), name="delete_doc"),
    path("doctors/export/", views.export_doctors, name="export_doctors"),
    # patient
    path("patients/", views.PatientListView.as_view(), name="patients"),
    path("patients/create", views.PatientCreateView.as_view(), name="create_pat"),
    path("patients/<pk>/update", views.PatientUpdateView.as_view(), name="update_pat"),
    path("patients/<pk>/delete", views.PatientDeleteView.as_view(), name="delete_pat"),
    path("patients/export/", views.export_patients, name="export_patients"),
    # insurance_company
    path(
        "insurance-companies/",
        views.InsuranceCompanyListView.as_view(),
        name="ins_companies",
    ),
    path(
        "insurance-companies/create",
        views.InsuranceCompanyCreateView.as_view(),
        name="create_ins_company",
    ),
    path(
        "insurance-companies/<pk>/update",
        views.InsuranceCompanyUpdateView.as_view(),
        name="update_ins_company",
    ),
    path(
        "insurance-companies/<pk>/delete",
        views.InsuranceCompanyDeleteView.as_view(),
        name="delete_ins_company",
    ),
    path(
        "insurance-companies/export/",
        views.export_ins_companies,
        name="export_ins_companies",
    ),
    # appointment
    path("appointments/", views.AppointmentListView.as_view(), name="appointments"),
    path("ajax/load-doctors", views.load_doctors, name="ajax_load_doctors"),
    path("ajax/load-talons", views.load_talons, name="ajax_load_talons"),
    path(
        "appointments/create", views.AppointmentCreateView.as_view(), name="create_app"
    ),
    path(
        "appointments/<pk>/update",
        views.AppointmentUpdateView.as_view(),
        name="update_app",
    ),
    path(
        "appointments/<pk>/delete",
        views.AppointmentDeleteView.as_view(),
        name="delete_app",
    ),
    path("appointments/export/", views.export_appointments, name="export_appointments"),
    # bill
    path("bills/", views.BillListView.as_view(), name="bills"),
    path("bills/create", views.BillCreateView.as_view(), name="create_bill"),
    path("bills/<pk>/update", views.BillUpdateView.as_view(), name="update_bill"),
    path("bills/<pk>/delete", views.BillDeleteView.as_view(), name="delete_bill"),
    path("bills/export/", views.export_bills, name="export_bills"),
    # payment
    path("payments/", views.PaymentListView.as_view(), name="payments"),
    path("payments/create", views.PaymentCreateView.as_view(), name="create_payment"),
    path(
        "payments/<pk>/update", views.PaymentUpdateView.as_view(), name="update_payment"
    ),
    path(
        "payments/<pk>/delete", views.PaymentDeleteView.as_view(), name="delete_payment"
    ),
    path("payments/export/", views.export_payments, name="export_payments"),
    # bill_payment
    path("bill-payments/", views.BillPaymentListView.as_view(), name="bill-payments"),
    path(
        "bill-payments/export/", views.export_bill_payments, name="export_bill_payments"
    ),
]

hospital/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
]

templates/bill/create.html
{% extends 'base_add.html' %}


{% block content %}
    <div class="container">
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">
                {{ form.errors }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        {% if form.appointment.field.queryset.count == 0 %}
            <div class="text-center my-3">
                <h3>Для всех приемов выписан счет</h3>
            </div>
            <div class="text-center my-3">
                <p>Хотите добавить новый прием?</p>
                <a href="{% url 'hospital:create_app' %}" class="btn btn-primary">Добавить прием</a>
            </div>
        {% else %}
            <form action="{% url 'hospital:create_bill' %}" method="post">
                {% csrf_token %}
                <div class="row justify-content-center mb-3">
                    <div class="col-md-6">
                        <label class="form-label" for="{{ form.appointment.id_for_label }}">Прием</label>
                        <div class="input-group">
                        <span class="input-group-text">
                            <i class="fa-solid fa-stethoscope"></i>
                        </span>
                            {{ form.appointment }}
                        </div>
                    </div>
                    <div class="col-md-3">
                        <label class="form-label" for="{{ form.amount.id_for_label }}">Сумма</label>
                        <div class="input-group">
                        <span class="input-group-text">
                            <i class="fa-solid fa-money"></i>
                        </span>
                            {{ form.amount }}
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary">Добавить счет</button>
                    </div>
                </div>
            </form>
        {% endif %}

    </div>

{% endblock %}

templates/bill/list.html
{% extends 'base_list.html' %}
{% load static %}


{% block css %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
{% endblock %}

{% block actions %}
    <div class="d-flex flex-row-reverse">
        <a href="{% url 'hospital:create_bill' %}" class="btn btn-primary my-1">Добавить счет</a>
        <a href="{% url 'hospital:export_bills' %}" class="btn btn-success mx-2 my-1">Выгрузить данные</a>
    </div>
{% endblock %}

{% block ths %}
    <th scope="col">Прием</th>
    <th scope="col">Застрахован ли пациент</th>
    <th scope="col">Дата отправления</th>
    <th scope="col">Сумма</th>
    <th scope="col">Действия</th>
{% endblock %}

{% block trs %}
    {% for bill in object_list %}
        <tr>
            <td class="align-middle">{{ bill.appointment }}</td>
            <td class="align-middle">{% if bill.is_amount_insured %}
                Да
            {% else %}
                Нет
            {% endif %}
            </td>
            <td class="align-middle">{{ bill.date_sent }}</td>
            <td class="align-middle">{{ bill.amount }} руб.</td>
            <td class="align-middle">
                <a href="{% url 'hospital:update_bill' bill.pk %}" class="btn btn-success">
                    <i class="fa-solid fa-edit"></i>
                </a>
                <a href="{% url 'hospital:delete_bill' bill.pk %}" class="btn btn-danger">
                    <i class="fa-solid fa-trash"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}