app/urls.py
from django.urls import path

from . import views

app_name = "hospital"

urlpatterns = [
    path("", views.index, name="index"),
    # doctor
    path("doctors/", views.DoctorListView.as_view(), name="doctors"),
    path("doctors/create", views.DoctorCreateView.as_view(), name="create_doc"),
    path("doctors/<pk>/update", views.DoctorUpdateView.as_view(), name="update_doc"),
    path("doctors/<pk>/delete", views.DoctorDeleteView.as_view(), name="delete_doc"),
    path("doctors/export/", views.export_doctors, name="export_doctors"),
    # patient
    path("patients/", views.PatientListView.as_view(), name="patients"),
    path("patients/create", views.PatientCreateView.as_view(), name="create_pat"),
    path("patients/<pk>/update", views.PatientUpdateView.as_view(), name="update_pat"),
    path("patients/<pk>/delete", views.PatientDeleteView.as_view(), name="delete_pat"),
    path("patients/export/", views.export_patients, name="export_patients"),
    # insurance_company
    path(
        "insurance-companies/",
        views.InsuranceCompanyListView.as_view(),
        name="ins_companies",
    ),
    path(
        "insurance-companies/create",
        views.InsuranceCompanyCreateView.as_view(),
        name="create_ins_company",
    ),
    path(
        "insurance-companies/<pk>/update",
        views.InsuranceCompanyUpdateView.as_view(),
        name="update_ins_company",
    ),
    path(
        "insurance-companies/<pk>/delete",
        views.InsuranceCompanyDeleteView.as_view(),
        name="delete_ins_company",
    ),
    path(
        "insurance-companies/export/",
        views.export_ins_companies,
        name="export_ins_companies",
    ),
    # appointment
    path("appointments/", views.AppointmentListView.as_view(), name="appointments"),
    path("ajax/load-doctors", views.load_doctors, name="ajax_load_doctors"),
    path("ajax/load-talons", views.load_talons, name="ajax_load_talons"),
    path(
        "appointments/create", views.AppointmentCreateView.as_view(), name="create_app"
    ),
    path(
        "appointments/<pk>/update",
        views.AppointmentUpdateView.as_view(),
        name="update_app",
    ),
    path(
        "appointments/<pk>/delete",
        views.AppointmentDeleteView.as_view(),
        name="delete_app",
    ),
    path("appointments/export/", views.export_appointments, name="export_appointments"),
    # bill
    path("bills/", views.BillListView.as_view(), name="bills"),
    path("bills/create", views.BillCreateView.as_view(), name="create_bill"),
    path("bills/<pk>/update", views.BillUpdateView.as_view(), name="update_bill"),
    path("bills/<pk>/delete", views.BillDeleteView.as_view(), name="delete_bill"),
    path("bills/export/", views.export_bills, name="export_bills"),
    # payment
    path("payments/", views.PaymentListView.as_view(), name="payments"),
    path("payments/create", views.PaymentCreateView.as_view(), name="create_payment"),
    path(
        "payments/<pk>/update", views.PaymentUpdateView.as_view(), name="update_payment"
    ),
    path(
        "payments/<pk>/delete", views.PaymentDeleteView.as_view(), name="delete_payment"
    ),
    path("payments/export/", views.export_payments, name="export_payments"),
    # bill_payment
    path("bill-payments/", views.BillPaymentListView.as_view(), name="bill-payments"),
    path(
        "bill-payments/export/", views.export_bill_payments, name="export_bill_payments"
    ),
]

hospital/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
]

app/forms.py
from django import forms
from app import models
from tempus_dominus.widgets import DatePicker


class DoctorCreationForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control py-2", "placeholder": "Введите имя"}
        )
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control py-2", "placeholder": "Введите фамилию"}
        )
    )

    surname = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control py-2", "placeholder": "Введите отчество"}
        )
    )

    specialty = forms.ModelChoiceField(
        queryset=models.Specialty.objects.all(),
        widget=forms.Select(
            attrs={
                "class": "form-select py-2",
                "placeholder": "Выберите специальность",
            }
        ),
    )

    phone_number = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control py-2",
                "placeholder": "Введите номер телефона",
            }
        )
    )

    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control py-2",
                "placeholder": "Введите адрес эл. почты",
            }
        )
    )

    address = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control py-2",
                "placeholder": "Введите адрес проживания",
            }
        )
    )

    class Meta:
        model = models.Doctor
        fields = (
            "first_name",
            "last_name",
            "surname",
            "specialty",
            "phone_number",
            "email",
            "address",
        )


class PatientCreationForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control py-2", "placeholder": "Введите имя"}
        )
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control py-2", "placeholder": "Введите фамилию"}
        )
    )

    surname = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control py-2", "placeholder": "Введите отчество"}
        )
    )

    phone_number = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control py-2",
                "placeholder": "Введите номер телефона",
            }
        )
    )

    address = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control py-2",
                "placeholder": "Введите адрес проживания",
            }
        )
    )

    insurance_company = forms.ModelChoiceField(
        queryset=models.InsuranceCompany.objects.all(),
        required=False,
        widget=forms.Select(
            attrs={
                "class": "form-select py-2",
                "placeholder": "Выберите страховую компанию",
            }
        ),
    )

    class Meta:
        model = models.Patient
        fields = (
            "first_name",
            "last_name",
            "surname",
            "phone_number",
            "address",
            "insurance_company",
        )


class InsuranceCompanyCreationForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control py-2",
                "placeholder": "Введите название компании",
            }
        )
    )

    phone_number = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control py-2",
                "placeholder": "Введите номер телефона",
            }
        )
    )

    address = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control py-2",
                "placeholder": "Введите адрес",
            }
        )
    )

    class Meta:
        model = models.InsuranceCompany
        fields = (
            "name",
            "phone_number",
            "address",
        )


class SpecialtyForm(forms.ModelForm):
    specialty = forms.ModelChoiceField(
        queryset=models.Specialty.objects.all(),
        widget=forms.Select(
            attrs={
                "class": "form-select py-2",
                "placeholder": "Выберите специальность",
            }
        ),
    )


class AppointmentCreationForm(forms.Form):
    patient = forms.ModelChoiceField(
        queryset=models.Patient.objects.all(),
        widget=forms.Select(
            attrs={
                "class": "form-select py-2",
                "placeholder": "Выберите пациента",
            }
        ),
    )

    specialty = forms.ModelChoiceField(
        queryset=models.Specialty.objects.all(),
        widget=forms.Select(
            attrs={
                "class": "form-select py-2",
                "placeholder": "Выберите специальность",
            }
        ),
    )

    doctor = forms.ModelChoiceField(
        queryset=models.Doctor.objects.all(),
        widget=forms.Select(
            attrs={
                "class": "form-select py-2",
                "placeholder": "Выберите доктора",
            }
        ),
    )

    talon = forms.ModelChoiceField(
        queryset=models.Talon.objects.all(),
        widget=forms.Select(
            attrs={
                "class": "form-select py-2",
                "placeholder": "Выберите доктора",
            }
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["doctor"].queryset = models.Doctor.objects.none()
        self.fields["talon"].queryset = models.Talon.objects.none()

    class Meta:
        fields = ("doctor", "patient", "specialty")


class BillCreationForm(forms.ModelForm):
    appointment = forms.ModelChoiceField(
        queryset=models.Appointment.objects.filter(bill__isnull=True),
        widget=forms.Select(
            attrs={
                "class": "form-select py-2",
                "placeholder": "Выберите прием",
            }
        ),
    )

    amount = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
                "class": "form-control py-2",
                "placeholder": "Введите счет за прием",
            }
        )
    )

    class Meta:
        model = models.Bill
        fields = (
            "appointment",
            "amount",
        )


class PaymentCreationForm(forms.ModelForm):
    bill = forms.ModelChoiceField(
        queryset=models.Bill.objects.all(),
        widget=forms.Select(
            attrs={
                "class": "form-select py-2",
                "placeholder": "Выберите страховую копанию",
            }
        ),
    )

    amount = forms.FloatField(
        widget=forms.NumberInput(
            attrs={
                "class": "form-control py-2",
                "placeholder": "Введите счет за прием",
            }
        )
    )

    date = forms.DateField(
        widget=DatePicker(
            attrs={
                "class": "form-control py-2",
                "placeholder": "Выберите дату",
            }
        )
    )

    class Meta:
        model = models.Payment
        fields = (
            "bill",
            "amount",
            "date",
        )

templates/appointment/create.html
{% extends 'base_add.html' %}


{% block content %}
    <div class="container">
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">
                {{ form.errors }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <form method="POST" id="appForm" data-doctors-url="{% url 'hospital:ajax_load_doctors' %}"
              data-talons-url="{% url 'hospital:ajax_load_talons' %}">
            {% csrf_token %}
            <div class="row justify-content-center mb-3">
                <div class="col-md-4">
                    <label class="form-label">Пациент</label>
                    <div class="input-group">
                        <span class="input-group-text">
                            <i class="fa-solid fa-person"></i>
                        </span>
                        {{ form.patient }}
                    </div>
                </div>
                <div class="col-md-4">
                    <label class="form-label">Специальность</label>
                    <div class="input-group">
                        <span class="input-group-text">
                            <i class="fa-solid fa-stethoscope"></i>
                        </span>
                        {{ form.specialty }}
                    </div>
                </div>
            </div>
            <div class="row justify-content-center mb-3">
                <div class="col-md-4">
                    <label class="form-label">Врач</label>
                    <div class="input-group">
                        <span class="input-group-text">
                            <i class="fa-solid fa-stethoscope"></i>
                        </span>
                        {{ form.doctor }}
                    </div>
                </div>
                <div class="col-md-4">
                    <label class="form-label">Талон</label>
                    <div class="input-group">
                        <span class="input-group-text">
                            <i class="fa-solid fa-clock"></i>
                        </span>
                        {{ form.talon }}
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-2">
                    <button type="submit" class="btn btn-primary">Добавить встречу</button>
                </div>
            </div>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $("#id_specialty").change(function () {
            var url = $("#appForm").attr("data-doctors-url");
            var specialtyId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'specialty': specialtyId
                },
                success: function (data) {
                    $("#id_doctor").html(data);
                }
            });

        });
        $("#id_doctor").change(function () {
            var url = $("#appForm").attr("data-talons-url");
            var docId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'doctor': docId
                },
                success: function (data) {
                    $("#id_talon").html(data);
                }
            });
        });
    </script>
{% endblock %}

templates/appointment/doctor_dropdown_list_options.html
<option value="">---------</option>
{% for doc in doctors %}
<option value="{{ doc.pk }}">{{ doc.full_name }}</option>
{% endfor %}

templates/appointment/list.html
{% extends 'base_list.html' %}
{% load static %}


{% block css %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
{% endblock %}

{% block actions %}
    <div class="d-flex flex-row-reverse">
        <a href="{% url 'hospital:create_app' %}" class="btn btn-primary my-1">Добавить прием</a>
        <a href="{% url 'hospital:export_appointments' %}" class="btn btn-success mx-2 my-1">Выгрузить данные</a>
    </div>
{% endblock %}

{% block ths %}
    <th scope="col">Доктор</th>
    <th scope="col">Пациент</th>
    <th scope="col">Дата и время</th>
    <th scope="col">Действия</th>
{% endblock %}

{% block trs %}
    {% for app in object_list %}
        <tr>
            <td class="align-middle">{{ app.doctor }}</td>
            <td class="align-middle">{{ app.patient }}</td>
            <td class="align-middle">{{ app.date }}, {{ app.time }}</td>
            <td class="align-middle">
                <a href="{% url 'hospital:update_app' app.pk %}" class="btn btn-success">
                    <i class="fa-solid fa-edit"></i>
                </a>
                <a href="{% url 'hospital:delete_app' app.pk %}" class="btn btn-danger">
                    <i class="fa-solid fa-trash"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

templates/appointment/talon_dropdown_list_options.html
<option value="">---------</option>
{% for talon in talons %}
<option value="{{ talon.pk }}">{{ talon }}</option>
{% endfor %}

templates/appointment/update.html
{% extends 'base_add.html' %}


{% block content %}
    <div class="container">
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">
                {{ form.errors }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <form method="POST" id="appForm" data-doctors-url="{% url 'hospital:ajax_load_doctors' %}"
              data-talons-url="{% url 'hospital:ajax_load_talons' %}" novalidate>
            {% csrf_token %}
            <div class="row justify-content-center mb-3">
                <div class="col-md-4">
                    <label class="form-label">Пациент</label>
                    <div class="input-group">
                        <span class="input-group-text">
                            <i class="fa-solid fa-person"></i>
                        </span>
                        {{ form.patient }}
                    </div>
                </div>
                <div class="col-md-4">
                    <label class="form-label">Специальность</label>
                    <div class="input-group">
                        <span class="input-group-text">
                            <i class="fa-solid fa-stethoscope"></i>
                        </span>
                        {{ form.specialty }}
                    </div>
                </div>
            </div>
            <div class="row justify-content-center mb-3">
                <div class="col-md-4">
                    <label class="form-label">Врач</label>
                    <div class="input-group">
                        <span class="input-group-text">
                            <i class="fa-solid fa-stethoscope"></i>
                        </span>
                        {{ form.doctor }}
                    </div>
                </div>
                <div class="col-md-4">
                    <label class="form-label">Талон</label>
                    <div class="input-group">
                        <span class="input-group-text">
                            <i class="fa-solid fa-clock"></i>
                        </span>
                        {{ form.talon }}
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-2">
                    <button type="submit" class="btn btn-primary">Изменить встречу</button>
                </div>
            </div>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                url: $("#appForm").attr("data-doctors-url"),
                data: {
                    'specialty': $("#id_specialty").val()
                },
                success: function (data) {
                    $("#id_doctor").html(data);
                }
            });

        })

        $("#id_doctor").change(function () {
            var url = $("#appForm").attr("data-talons-url");
            var docId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'doctor': docId
                },
                success: function (data) {
                    $("#id_talon").html(data);
                }
            });
        });
        {% comment %}$("#id_specialty").change(function () {
            var url = $("#appForm").attr("data-doctors-url");
            var specialtyId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'specialty': specialtyId
                },
                success: function (data) {
                    $("#id_doctor").html(data);
                }
            });

        });
        {% endcomment %}
    </script>
{% endblock %}