app/urls.py
from django.urls import path

from . import views

app_name = "hospital"

urlpatterns = [
    path("", views.index, name="index"),
    # doctor
    path("doctors/", views.DoctorListView.as_view(), name="doctors"),
    path("doctors/create", views.DoctorCreateView.as_view(), name="create_doc"),
    path("doctors/<pk>/update", views.DoctorUpdateView.as_view(), name="update_doc"),
    path("doctors/<pk>/delete", views.DoctorDeleteView.as_view(), name="delete_doc"),
    path("doctors/export/", views.export_doctors, name="export_doctors"),
    # patient
    path("patients/", views.PatientListView.as_view(), name="patients"),
    path("patients/create", views.PatientCreateView.as_view(), name="create_pat"),
    path("patients/<pk>/update", views.PatientUpdateView.as_view(), name="update_pat"),
    path("patients/<pk>/delete", views.PatientDeleteView.as_view(), name="delete_pat"),
    path("patients/export/", views.export_patients, name="export_patients"),
    # insurance_company
    path(
        "insurance-companies/",
        views.InsuranceCompanyListView.as_view(),
        name="ins_companies",
    ),
    path(
        "insurance-companies/create",
        views.InsuranceCompanyCreateView.as_view(),
        name="create_ins_company",
    ),
    path(
        "insurance-companies/<pk>/update",
        views.InsuranceCompanyUpdateView.as_view(),
        name="update_ins_company",
    ),
    path(
        "insurance-companies/<pk>/delete",
        views.InsuranceCompanyDeleteView.as_view(),
        name="delete_ins_company",
    ),
    path(
        "insurance-companies/export/",
        views.export_ins_companies,
        name="export_ins_companies",
    ),
    # appointment
    path("appointments/", views.AppointmentListView.as_view(), name="appointments"),
    path("ajax/load-doctors", views.load_doctors, name="ajax_load_doctors"),
    path("ajax/load-talons", views.load_talons, name="ajax_load_talons"),
    path(
        "appointments/create", views.AppointmentCreateView.as_view(), name="create_app"
    ),
    path(
        "appointments/<pk>/update",
        views.AppointmentUpdateView.as_view(),
        name="update_app",
    ),
    path(
        "appointments/<pk>/delete",
        views.AppointmentDeleteView.as_view(),
        name="delete_app",
    ),
    path("appointments/export/", views.export_appointments, name="export_appointments"),
    # bill
    path("bills/", views.BillListView.as_view(), name="bills"),
    path("bills/create", views.BillCreateView.as_view(), name="create_bill"),
    path("bills/<pk>/update", views.BillUpdateView.as_view(), name="update_bill"),
    path("bills/<pk>/delete", views.BillDeleteView.as_view(), name="delete_bill"),
    path("bills/export/", views.export_bills, name="export_bills"),
    # payment
    path("payments/", views.PaymentListView.as_view(), name="payments"),
    path("payments/create", views.PaymentCreateView.as_view(), name="create_payment"),
    path(
        "payments/<pk>/update", views.PaymentUpdateView.as_view(), name="update_payment"
    ),
    path(
        "payments/<pk>/delete", views.PaymentDeleteView.as_view(), name="delete_payment"
    ),
    path("payments/export/", views.export_payments, name="export_payments"),
    # bill_payment
    path("bill-payments/", views.BillPaymentListView.as_view(), name="bill-payments"),
    path(
        "bill-payments/export/", views.export_bill_payments, name="export_bill_payments"
    ),
]

hospital/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>

    <!-- Bootstrap CSS (jsDelivr CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- Bootstrap Bundle JS (jsDelivr CDN) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>

    <!-- Icons -->
    <script src="https://kit.fontawesome.com/8e12b3c561.js" crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}
</head>

<body>
<div class="header bg-light">
    <div class="container">
        <header class="p-3 text-white">
            <div class="container">
                <div class="d-flex justify-content-center">
                    <ul class="nav nav-pills">
                        <li><a href="#" class="nav-link px-2 text-black fs-40">Врачи</a></li>
                        <li><a href="#" class="nav-link px-2 text-secondary fs-18">Features</a></li>
                        <li><a href="#" class="nav-link px-2 text-secondary fs-18">Pricing</a></li>
                        <li><a href="#" class="nav-link px-2 text-secondary fs-18">FAQs</a></li>
                        <li><a href="#" class="nav-link px-2 text-secondary fs-18">About</a></li>
                    </ul>
                </div>

            </div>
        </header>
    </div>
</div>

<div class="container">
    {% if header %}
        <h1 class="text-center mx-auto my-2">{{ header }}</h1>
    {% endif %}
    {% block actions %} {% endblock %}

    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0">
                    <div class="table-responsive table-scroll" data-mdb-perfect-scrollbar="true"
                         style="position: relative; height: 700px">
                        <table class="table table-hover mb-0">
                            <thead style="background-color: #002d72;" class="py-3">
                            <tr>
                                {% block ths %} {% endblock %}
                            </tr>
                            </thead>
                            <tbody>
                            {% block trs %} {% endblock %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/base_add.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>

    <!-- Bootstrap CSS (jsDelivr CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- Bootstrap Bundle JS (jsDelivr CDN) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>

    <!-- Icons -->
    <script src="https://kit.fontawesome.com/8e12b3c561.js" crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>

    {# Django Tempus Dominus assets are included in `{{ form.media }}` #}
    {{ form.media }}
</head>
<body>
{% include 'header.html' %}

{% block content %} {% endblock %}

</body>
</html>

templates/base_list.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>

    <!-- Bootstrap CSS (jsDelivr CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- Bootstrap Bundle JS (jsDelivr CDN) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>

    <!-- Icons -->
    <script src="https://kit.fontawesome.com/8e12b3c561.js" crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}
</head>

<body>
{% include 'header.html' %}


<div class="container">
    {% if header %}
        <h1 class="text-center mx-auto my-2">{{ header }}</h1>
    {% endif %}
    {% block actions %} {% endblock %}

    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0">
                    <div class="table-responsive table-scroll" data-mdb-perfect-scrollbar="true"
                         style="position: relative; height: 800px">
                        <table class="table table-hover mb-0">
                            <thead style="background-color: #002d72;" class="py-3">
                            <tr>
                                {% block ths %} {% endblock %}
                            </tr>
                            </thead>
                            <tbody>
                            {% block trs %} {% endblock %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/confirm_delete.html
{% extends 'base_add.html' %}

{% block content %}
    <div class="container">
        <div class="row my-4 justify-content-center">
            <div class="col-md-4">
                <div class="card text-center">
                    <h5 class="card-header">{{ title }}</h5>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            <div class="card-title">Вы уверены что хотите удалить "{{ object }}"?</div>
                            {{ form }}
                            <input class="btn btn-danger" type="submit" value="Удалить">
                            <a href="../" class="btn btn-primary">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/header.html
<div class="header bg-light">
    <div class="container">
        <header class="p-3 text-white">
            <div class="container">
                <div class="d-flex justify-content-center">
                    <ul class="nav nav-pills">
                        <li>
                            <a href="{% url 'hospital:doctors' %}"
                               class="nav-link px-2 {% if request.path == '/doctors/' %}text-black{% else %}text-secondary{% endif %} fs-18">
                                Врачи
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'hospital:patients' %}"
                               class="nav-link px-2 {% if request.path == '/patients/' %}text-black{% else %}text-secondary{% endif %} fs-18">
                                Пациенты
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'hospital:ins_companies' %}"
                               class="nav-link px-2 {% if request.path == '/insurance-companies/' %}text-black{% else %}text-secondary{% endif %} fs-18">
                                Страховые компании
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'hospital:appointments' %}"
                               class="nav-link px-2 {% if request.path == '/appointments/' %}text-black{% else %}text-secondary{% endif %} fs-18">
                                Приемы
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'hospital:bills' %}"
                               class="nav-link px-2 {% if request.path == '/bills/' %}text-black{% else %}text-secondary{% endif %} fs-18">
                                Счета
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'hospital:payments' %}"
                               class="nav-link px-2 {% if request.path == '/payments/' %}text-black{% else %}text-secondary{% endif %} fs-18">
                                Платежи
                            </a>
                        </li>
                        <li><a href="{% url 'hospital:bill-payments' %}"
                               class="nav-link px-2 {% if request.path == '/bill-payments/' %}text-black{% else %}text-secondary{% endif %} fs-18">
                            Счета и платежи
                        </a></li>
                    </ul>
                </div>
            </div>
        </header>
    </div>
</div>